### ISSUE TITLE
runningroutes admin: import numpy failure in production environment

### ISSUE THREAD

**Issue by louking** [louking/steeps#209]
See http://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html#virtual-environment-and-python-version

virtualenv
```
(routetilityvenv) [sandboxsteeps@loutilities admin]$ python
Python 2.7.11 (default, May 29 2016, 13:20:50)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
```

runtime
`[Mon Dec 25 08:44:32.616819 2017] [:error] [pid 17673] started with python 2.7.5, GCC 4.8.5 20150623 (Red Hat 4.8.5-16)`

Maybe just reinstall virtual environment using standard system python.
```
mod_wsgi (pid=16007): Target WSGI script '/var/www/sandbox.steeplechasers.org/wordpress/wp-content/themes/steeps/runningroutes/admin/runningroutes.wsgi' cannot be loaded as Python module.
mod_wsgi (pid=16007): Exception occurred processing WSGI script '/var/www/sandbox.steeplechasers.org/wordpress/wp-content/themes/steeps/runningroutes/admin/runningroutes.wsgi'.
Traceback (most recent call last):
  File "/var/www/sandbox.steeplechasers.org/wordpress/wp-content/themes/steeps/runningroutes/admin/runningroutes.wsgi", line 37, in <module>
    from runningroutes import app as application
  File "/var/www/sandbox.steeplechasers.org/wordpress/wp-content/themes/steeps/runningroutes/admin/runningroutes/__init__.py", line 61, in <module>
    import runningroutesadmin
  File "/var/www/sandbox.steeplechasers.org/wordpress/wp-content/themes/steeps/runningroutes/admin/runningroutes/runningroutesadmin.py", line 26, in <module>
    import numpy
  File "/var/www/sandbox.steeplechasers.org/routetilityvenv/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/var/www/sandbox.steeplechasers.org/routetilityvenv/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/var/www/sandbox.steeplechasers.org/routetilityvenv/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/var/www/sandbox.steeplechasers.org/routetilityvenv/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/var/www/sandbox.steeplechasers.org/routetilityvenv/lib/python2.7/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /var/www/sandbox.steeplechasers.org/routetilityvenv/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS2_AsUTF8String

```

**Comment by louking** [comment]
Resolved by reinstalling virtual environment with standard python that came with CentOS
